/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xF8, 0x97, 0x8E, 0x25, 0x42, 0x72, 0x4E, 0x14}

#define VIAL_UNLOCK_COMBO_ROWS { 2, 3, 0, 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1, 0, 2, 4 }

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT

#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4
#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 120
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 1000
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 80
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 175
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)
